    <dialog id="legal-panel">
        <button id="legal-close" class="btn-icon" type="button" aria-label="Cerrar">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="6" y1="6" x2="18" y2="18"/><line x1="18" y1="6" x2="6" y2="18"/></svg>
        </button>
        <h3>Aviso Legal, Privacidad y Cookies</h3>
        <p>En estricto cumplimiento del <strong>Artículo 18 de la Constitución Española</strong> (derecho a la intimidad), el <strong>Reglamento General de Protección de Datos (RGPD)</strong>, la <strong>LSSI-CE</strong> y la <strong>Ley 37/2007 de reutilización de la información del sector público</strong>, informamos de lo siguiente:</p>
        <p><strong>Propiedad intelectual y licencia:</strong> El código fuente, el diseño y los iconos de esta aplicación son obra de Yeray Garrido y se publican bajo la licencia <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.es" target="_blank" rel="noopener noreferrer">Creative Commons Reconocimiento-NoComercial-CompartirIgual 4.0 (CC BY-NC-SA 4.0)</a>: puedes copiarlos y adaptarlos citando a su autor, sin fines comerciales y compartiendo las obras derivadas bajo la misma licencia. Los datos de transporte pertenecen a sus operadores y se rigen por sus propias licencias (ver «Fuentes de datos» más abajo). Los nombres y logotipos de Bizkaibus, Metro Bilbao, Euskotren y Renfe son de sus respectivos titulares y esta aplicación no tiene relación con ellos.</p>
        <p><strong>Identidad del responsable:</strong> Proyecto independiente desarrollado sin ánimo de lucro por Yeray Garrido. BizkaiBus+, Metro+, Euskotren+, Tranvía Bilbao+, Tranvía Vitoria+ y Renfe Cercanías+ son proyectos independientes, sin afiliación ni respaldo de Bizkaibus, Metro Bilbao S.A., el Consorcio de Transportes de Bizkaia, Euskotren, Renfe ni la Diputación Foral de Bizkaia.</p>
        <p><strong>Privacidad y Analíticas:</strong> Utilizamos <strong>Vercel Web Analytics</strong> (herramienta respetuosa con la privacidad y libre de cookies) para recoger estadísticas básicas y anónimas de uso (visitas, país, dispositivo). Vercel procesa las direcciones IP temporalmente para generar estas métricas agrupadas, actuando como encargado del tratamiento. Aparte de esto, la app <strong>no recopila, almacena ni cede ningún dato personal tuyo</strong>.</p>
        <p><strong>Política de Cookies y almacenamiento local:</strong> No usamos cookies de terceros ni de rastreo. Únicamente empleamos el almacenamiento de tu propio dispositivo (<code>localStorage</code> e <code>IndexedDB</code>) para guardar tus paradas "Favoritas", el "Tema", el idioma elegido y, si los activas, tus avisos de incidencias por línea; todo queda solo en tu dispositivo. Al ser almacenamiento puramente técnico y solicitado por ti, está exento de banner de consentimiento según el Art. 22.2 de la LSSI.</p>
        <p><strong>Ubicación:</strong> Si pulsas «Cerca de mí», tu navegador te pide permiso y la ubicación se envía solo para buscar las paradas más cercanas, sin guardarse. Esta búsqueda necesita conexión a internet.</p>
        <p><strong>Modo sin conexión:</strong> La app guarda en tu dispositivo lo último que consultaste con conexión (paradas y horarios de líneas ya vistos), para que puedas volver a verlo sin internet. No se actualiza mientras estés sin conexión, y los horarios en tiempo real, la posición de los buses en el mapa, los avisos de incidencias y «Cerca de mí» necesitan conexión: no funcionan en modo sin conexión ni con datos que no hayas consultado antes.</p>
        <p><strong>Fuentes de datos y exención de responsabilidad:</strong> Los horarios estáticos y, cuando existe, el tiempo real proceden de las fuentes oficiales de cada operador: BizkaiBus+ (Bizkaibus / Open Data Bizkaia, CC-BY 4.0), Metro+ (horario y tiempo real de Metro Bilbao publicados por el Consorcio de Transportes de Bizkaia / data.ctb.eus, CC-BY 4.0), Euskotren+, Tranvía Bilbao+ y Tranvía Vitoria+ (Euskotren / Open Data Euskadi, CC-BY 4.0), Renfe Cercanías+ (Renfe / NAP, Punto de Acceso Nacional de Transporte), publicados sin alterarlos. Euskotren+, Tranvía Bilbao+, Tranvía Vitoria+ y Renfe Cercanías+ muestran el horario programado oficial: no reflejan retrasos, adelantos ni cancelaciones, salvo los avisos de incidencias que publique el propio operador. Si un tren o tranvía va con retraso y el operador no lo publica, la app no puede saberlo. El mapa en vivo de Bizkaibus usa teselas de © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a>, cuyos datos también se han usado para asignar zona o barrio a las paradas. En Metro+, los tiempos «en directo» son la previsión de llegada que publica el Consorcio de Transportes de Bizkaia y la app la asocia a cada tren del horario oficial; si la previsión no está disponible se muestra el horario programado. En Bizkaibus, la posición de los vehículos y el tiempo estimado de llegada son una estimación calculada a partir de la posición GPS que publica el operador y pueden no coincidir exactamente con la realidad: no los uses como única referencia para no perder un servicio. No garantizamos la exactitud, actualidad ni disponibilidad continua de estos datos; esta aplicación es meramente informativa y su uso es responsabilidad exclusiva de quien la utiliza. Del mismo modo, no nos hacemos responsables de la puntualidad, frecuencia, cancelaciones ni de la calidad o eficacia del propio servicio de transporte: eso depende exclusivamente del operador que presta el servicio y publica los datos, no de esta aplicación. Los cálculos que hace la app (por ejemplo, combinar horarios, estimar retrasos o agrupar viajes) se basan siempre en los datos que publica cada operador: si esos datos de origen están mal o desactualizados, el resultado mostrado puede heredar ese error, y no somos responsables de fallos que vengan de la fuente original y no de nuestro propio procesamiento.</p>
        <p><strong>Contacto.</strong> <a href="https://www.yeraygarrido.dev/" target="_blank" rel="noopener noreferrer">yeraygarrido.dev</a></p>
    </dialog>
